[package]
name = "metrics_collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.23.5"
arrayvec = "0.7.2"
procfs = "0.12.0"
rust_decimal = "1.22.0"